version: '3.8'

services:
  # Main Application
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/neonmurer
      - JWT_SECRET=your-very-secure-jwt-secret-here-change-in-production
      - BCRYPT_ROUNDS=12
      - PORT=3001
      - MAX_FILE_SIZE=10mb
      - ANALYTICS_ENABLED=true
      - LOG_LEVEL=info
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./content:/app/content
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=neonmurer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis (Optional - for sessions/caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
